### ISSUE TITLE
fake-bpy-module adds stand alone modules

### ISSUE THREAD

**Issue by nutti** [Korchy/blender_autocomplete#1]
Hi,

I'm a developer of [fake-bpy-module](https://github.com/nutti/fake-bpy-module).
I recently found that [your blog post](https://b3d.interplanety.org/en/using-external-ide-pycharm-for-writing-blender-scripts/) refers my project page. Thanks.

And, I found that your pre-generated modules are obsoleted.
Recently, I uploaded [pre-generated modules](https://github.com/nutti/fake-bpy-module/releases) in my project page as well as pip package.
New version supports type hint feature which enables to complete more codes than ever.

If you don't mind, I'm appreciate to refer the release page.

Thanks.

**Comment by Korchy** [comment]
Hello!
I updated modules and add a direct link to your release page in readme.
Thank you for your support!
