### ISSUE TITLE
Undefined Reference Operator

### ISSUE THREAD

**Issue by KulaGGin** [Korchy/blender_autocomplete#4]
I'm trying to setup environment to make a plugin, getting this error in PyCharm after following [the article](https://b3d.interplanety.org/en/using-external-ide-pycharm-for-writing-blender-scripts/) that says on how to setup everything.

I git cloned the repository(instead of downloading the last release).

My info from system-info.txt:
```
Blender:
=====================================
version: 2.92.0, branch: master, commit date: 2021-02-24 16:25, hash: 02948a2cab44, type: Release
build date: 2021-02-25, 09:31:14

Python:
=====================================
version: 3.7.7 (default, Jun 13 2020, 11:11:23) [MSC v.1916 64 bit (AMD64)]
```

I have the exact same interpreter selected in PyCharm as Blender uses, I have copied all files from the 2.92 directory from this repository to blender directory:
![jP6Legm1xk](https://user-images.githubusercontent.com/16989713/116284816-2c97a200-a796-11eb-8f93-9e06e8301a25.png)

And I have this directory in include path list for the respective 3.7.7 python interpreter:
![pycharm64_L8aT0Y4GBA](https://user-images.githubusercontent.com/16989713/116284861-37eacd80-a796-11eb-8aef-5d9116c5b147.png)

The autocomplete works:
![pycharm64_1lxbLS1lLL](https://user-images.githubusercontent.com/16989713/116284917-489b4380-a796-11eb-9236-11f071999942.png)

But I'm still getting the error for the `Operator` symbol. The addon works in Blender when I install the `.py` file as an addon.

Not sure what is it. How were these files for autocomplete made? Can I add this missing `Operator` symbol myself?

**Comment by KulaGGin** [comment]
Oh well, I git cloned the repository instead of downloading the release.

I just pasted files from 2.92 directory from the release version and `Undefined Reference Operator` error is gone.

Well, this just might be useful to you since you updated this repo many times since the last release.

Thank you for your work.

**Comment by Korchy** [comment]
Hi!

Thank you for the feedback! Glad, that you solved your problem.

---
Nikita

вт, 27 апр. 2021 г. в 20:45, KulaGGin ***@***.***>:
